{
 "title": "Energy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Energy monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Voltage (V)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"OpenDataIoT\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"WS1\" and\n    r._field == \"bus\" or\n    r._field == \"load\" or\n    r._field == \"shunt\"\n  )\n"
    }
   ]
  },
  {
   "title": "Current (mA)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"OpenDataIoT\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"WS1\" and\n    r._field == \"currentmA\"\n  )"
    }
   ]
  },
  {
   "title": "Power (mW)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"OpenDataIoT\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"WS1\" and\n    r._field == \"powermW\"\n  )"
    }
   ]
  }
 ]
}