{
 "title": "Weather",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Current values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "text", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 }, "options": { "content": "# Weather station\n# WS1" } },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"OpenDataIoT\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"WS1\" and\n    r._field == \"temperature\"\n  )"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"OpenDataIoT\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"WS1\" and\n    r._field == \"humidity\"\n  )"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"OpenDataIoT\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"WS1\" and\n    r._field == \"pressure\"\n  )"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"OpenDataIoT\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"WS1\" and\n    r._field == \"light_intensity\"\n  )"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"OpenDataIoT\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"WS1\" and\n    r._field == \"wind_speed\"\n  )"
    }
   ]
  },
  { "title": "Weather parameters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Temperature (°C)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"OpenDataIoT\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"WS1\" and\n    r._field == \"temperature\"\n  )"
    }
   ]
  },
  {
   "title": "Humidity (%)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"OpenDataIoT\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"WS1\" and\n    r._field == \"humidity\"\n  )"
    }
   ]
  },
  {
   "title": "Pressure (hPa)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "from(bucket: \"OpenDataIoT\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"WS1\" and\n    r._field == \"pressure\"\n  )"
    }
   ]
  },
  {
   "title": "Light intensity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"OpenDataIoT\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"WS1\" and\n    r._field == \"light_intensity\"\n  )"
    }
   ]
  },
  {
   "title": "Wind speed (Km/h)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"OpenDataIoT\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"WS1\" and\n    r._field == \"wind_speed\"\n  )"
    }
   ]
  }
 ]
}